name: first-workflow
on:
  push:

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo "Hello world"
      - name: multiple line command
        run: |
          node -v
          npm -v
